[build-system]
build-backend = "setuptools.build_meta"
requires = ["setuptools", "setuptools-scm"]

[project]
authors = [{name = "ArviZ Developers"}]
classifiers = [
  "Development Status :: 1 - Planning",
  "Intended Audience :: Science/Research",
  "Intended Audience :: Education",
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.8",
  "Topic :: Scientific/Engineering",
  "Topic :: Scientific/Engineering :: Visualization",
  "Topic :: Scientific/Engineering :: Mathematics",
]
dependencies = ["arviz", "jupyterlab", "panel"]
description = "Bayesian Dashboards built on top of Panel"
keywords = ["bayesian", "statistics", "Visualization"]
license = {file = "LICENSE"}
maintainers = []
name = "arviz_dashboard"
readme = {file = "README.md", content-type = "text/markdown"}
requires-python = ">=3.8"
version = "0.0.1"

[project.optional-dependencies]
dev = ["black", "flake8", "isort", "pre-commit", "pyre-check", "ruff"]

[project.urls]
"Bug Tracker" = "https://github.com/arviz-devs/arviz_dashboard/issues"
Homepage = "https://www.arviz.org"
"Source Code" = "https://github.com/arviz-devs/arviz_dashboard"

[tool.flake8]
max-line-length = 88

[tool.isort]
line_length = 88
profile = "black"

[tool.ruff]
per-file-ignores = {"__init__.py" = ["F401"]}
